### PR TITLE
Issue 423

### PR DESCRIPTION
**Pull request by cquest**
Initial bucket fill rerun was done after testing autocomplete and other things... so no rerun was done in case autocomplete=false

### CODE REVIEW

**Comment by yohanboniface** [comment]
> so no rerun was done in case autocomplete=false

But only if `helper.has_cream() and helper.cream < config.BUCKET_MIN` also returns True, right?
So if we have cream (at least one zuper gut result) and less than BUCKET_MIN of this cream, there is probably no need to rerun the query.
Of do you have a specific case where this is an issue?

**Comment by cquest** [comment]
An explain will explain everything...

> EXPLAIN allee des acacias LIMIT 50 AUTOCOMPLETE 0
[1.604] Taken tokens: [<Token acacias>]
[1.629] Common tokens: [<Token allee>, <Token des>]
[1.640] Housenumbers token: []
[1.647] Not found tokens: []
[1.659] Filters: []
[1.675] ** ONLY_COMMONS_BUT_GEOHASH_TRY_AUTOCOMPLETE_COLLECTOR **
[1.687] ** NO_TOKENS_BUT_HOUSENUMBERS_AND_GEOHASH **
[1.696] ** NO_AVAILABLE_TOKENS_ABORT **
[1.704] ** ONLY_COMMONS **
[1.716] ** NO_MEANINGFUL_BUT_COMMON_TRY_AUTOCOMPLETE_COLLECTOR **
[1.724] ** ONLY_COMMONS_TRY_AUTOCOMPLETE_COLLECTOR **
[1.733] ** BUCKET_WITH_MEANINGFUL **
[1.763] New bucket with keys ['w|acacias', 'w|allee'] and limit 10
**[4.744] 10 ids in bucket so far**
**[4.784] Checking cream.**

The first limited search is not rerun because of autocomplete=0

With the fix:

> EXPLAIN allee des acacias LIMIT 50 AUTOCOMPLETE 0
[6.680] Taken tokens: [<Token acacias>]
[6.693] Common tokens: [<Token allee>, <Token des>]
[6.696] Housenumbers token: []
[6.699] Not found tokens: []
[6.703] Filters: []
[6.710] ** ONLY_COMMONS_BUT_GEOHASH_TRY_AUTOCOMPLETE_COLLECTOR **
[6.715] ** NO_TOKENS_BUT_HOUSENUMBERS_AND_GEOHASH **
[6.719] ** NO_AVAILABLE_TOKENS_ABORT **
[6.721] ** ONLY_COMMONS **
[6.726] ** NO_MEANINGFUL_BUT_COMMON_TRY_AUTOCOMPLETE_COLLECTOR **
[6.729] ** ONLY_COMMONS_TRY_AUTOCOMPLETE_COLLECTOR **
[6.732] ** BUCKET_WITH_MEANINGFUL **
[6.744] New bucket with keys ['w|acacias', 'w|allee'] and limit 10
**[8.052] 10 ids in bucket so far**
[8.061] New bucket with keys ['w|acacias', 'w|allee'] and limit 0
**[9.023] 100 ids in bucket so far**
[9.033] ** REDUCE_WITH_OTHER_COMMONS **
[9.040] Now considering also common token des
[9.046] New bucket with keys ['w|acacias', 'w|allee', 'w|des'] and limit 0
[10.12] 100 ids in bucket so far
[10.14] ** ENSURE_GEOHASH_RESULTS_ARE_INCLUDED_IF_CENTER_IS_GIVEN **
[10.16] ** FUZZY_COLLECTOR **
[10.17] ** AUTOCOMPLETE_MEANINGFUL_COLLECTOR **
[10.18] ** EXTEND_RESULTS_REDUCING_TOKENS **
[10.19] ** EXTEND_RESULTS_EXTRAPOLING_RELATIONS **
[10.20] Computing results
[10.23] Done getting results data
[46.23] Done computing results

**Comment by yohanboniface** [comment]
> [4.744] 10 ids in bucket so far
[4.784] Checking cream.
The first limited search is not rerun because of autocomplete=0

It should be, after the cream has been checked (and thus some results already fetched from the DS and such). Can you share the whole output?

**Comment by cquest** [comment]
> EXPLAIN allee des acacias LIMIT 50 AUTOCOMPLETE 0
[8.270] Taken tokens: [<Token acacias>]
[8.308] Common tokens: [<Token allee>, <Token des>]
[8.320] Housenumbers token: []
[8.328] Not found tokens: []
[8.341] Filters: []
[8.362] ** ONLY_COMMONS_BUT_GEOHASH_TRY_AUTOCOMPLETE_COLLECTOR **
[8.399] ** NO_TOKENS_BUT_HOUSENUMBERS_AND_GEOHASH **
[8.411] ** NO_AVAILABLE_TOKENS_ABORT **
[8.421] ** ONLY_COMMONS **
[8.435] ** NO_MEANINGFUL_BUT_COMMON_TRY_AUTOCOMPLETE_COLLECTOR **
[8.444] ** ONLY_COMMONS_TRY_AUTOCOMPLETE_COLLECTOR **
[8.454] ** BUCKET_WITH_MEANINGFUL **
[8.487] New bucket with keys ['w|acacias', 'w|allee'] and limit 10
[11.65] 10 ids in bucket so far
[11.70] Checking cream.
[11.71] Computing results
[11.73] Done getting results data
[24.24] Done computing results
[24.35] Cream found. Returning.
[24.36] Computing results
[24.40] Done computing results

As you can see, after cheking cream no rerun is done even if we only have 10 candidates in the bucket and asked for 50 (dans there's much more available in the indexed data).

**Comment by yohanboniface** [comment]
> [8.270] Taken tokens: []
[8.308] Common tokens: [, ]
[8.320] Housenumbers token: []
[8.328] Not found tokens: []

Those lines are weird. Which db are your running on? Are you running the shell with the same config as the one used for the import?

**Comment by yohanboniface** [comment]
> [8.487] New bucket with keys ['w|acacias', 'w|allee'] and limit 10
[11.65] 10 ids in bucket so far
[11.70] Checking cream.
[11.71] Computing results
[11.73] Done getting results data
[24.24] Done computing results
[24.35] Cream found. Returning.

This means that cream has been found but less than the asked 10 results, so there is a shortcut here asking to stop the heuristic.

**Comment by cquest** [comment]
Oups...

> EXPLAIN allee des acacias **LIMIT 20** AUTOCOMPLETE 0
[9.897] Taken tokens: [<Token akasia>]
[9.922] Common tokens: [<Token ale>, <Token de>]
[9.930] Housenumbers token: []
[9.937] Not found tokens: []
[9.946] Filters: []
[9.961] ** ONLY_COMMONS_BUT_GEOHASH_TRY_AUTOCOMPLETE_COLLECTOR **
[9.972] ** NO_TOKENS_BUT_HOUSENUMBERS_AND_GEOHASH **
[9.982] ** NO_AVAILABLE_TOKENS_ABORT **
[9.986] ** ONLY_COMMONS **
[9.992] ** NO_MEANINGFUL_BUT_COMMON_TRY_AUTOCOMPLETE_COLLECTOR **
[9.997] ** ONLY_COMMONS_TRY_AUTOCOMPLETE_COLLECTOR **
[10.00] ** BUCKET_WITH_MEANINGFUL **
[10.01] New bucket with keys ['w|akasia', 'w|ale'] and limit 10
**[12.44] 10 ids in bucket so far**
**[12.47] Checking cream.
[12.48] Computing results**
[12.50] Done getting results data
[19.28] Done computing results
[19.33] Cream found. Returning.
[19.33] Computing results
[19.34] Done computing results
Allée des Acacias 36000 Châteauroux (v9lk5 | importance: 0.0306/0.1, str_distance: 1.0/1.0)
Allée des Acacias 31500 Toulouse (GY5WL | importance: 0.0268/0.1, str_distance: 1.0/1.0)
Allée des Acacias 79000 Niort (pmW4Q | importance: 0.0249/0.1, str_distance: 1.0/1.0)
Allée des Acacias 87280 Limoges (gqJNY | importance: 0.0246/0.1, str_distance: 1.0/1.0)
Allée des Acacias 63100 Clermont-Ferrand (p6zqr | importance: 0.022/0.1, str_distance: 1.0/1.0)
Allée Acacias 97413 Cilaos (mm4zr | importance: 0.003/0.1, str_distance: 0.75/1.0)
Allée Acacias 78600 Le Mesnil-le-Roi (JxK8v | importance: 0.0023/0.1, str_distance: 0.75/1.0)
Allée Acacias 37260 Artannes-sur-Indre (kOBk6 | importance: 0.0022/0.1, str_distance: 0.75/1.0)
Allée Acacias 44850 Le Cellier (GzZ6Q | importance: 0.0018/0.1, str_distance: 0.75/1.0)
Allée Acacias 80800 Vecquemont (xrqVq | importance: 0.001/0.1, str_distance: 0.75/1.0)
19.4 ms — 1 run(s) — **10 results**

A rerun is missing.

**Pull request closed without merging**
