### PR TITLE
Fix missing reverse token <=> housenumber pair index

### PR DESCRIPTION
**Pull request by yohanboniface**
Needs more work.

### CODE REVIEW

**Comment by davidbgk** [comment]
Reminder: do not forget to deindex too!

**Comment by davidbgk** [comment]
Whatever I try, I have a 20-25% decrease in performances. The bottleneck being Redis :(
On the other side, it's relatively normal given that we pass a lot more keys within the passed set.

**Comment by davidbgk** [comment]
I tried to change the `BATCH_CHUNK_SIZE` setting up and down without any benefit in our case :(

**Comment by yohanboniface** [comment]
Raw diff when trying, without success, to only index one way pairs.

The goal was to reduce DB size and index time.
The idea was to only index one way pairs, i.e. instead of adding "rue" in "p|lilas" and "lila" in "p|rue", to only add one of those. And then, at query time, either to use alphanumerical order to define which key to use, or to query both through a Lua script.
The issue is that we do not use pair index only for one to one query (i.e. is "rue" ever used with "lilas"?), but we use intersection, in two scenarios, autocomplete and fuzzy computing, to reduce candidates.
Let's take autocomplete example.
Say someone search for "rue des lil…", we want to autocomplete "lil".
This will be done using the "edgengram index", which looks like:

    n|lil => lilas, lille, liliputien…

But this could return a lot of candidates. What we do is to reduce the candidates by filtering only those that have been seen at least once with the other words of the query ("rue" and "des" in our example).
This is done by intersecting with the pair index, that looks like:

    p|rue => de, du, la, chênes, …, lilas, lille…
    p|des => rue, chênes, …, lilas…

So this means that in this case we need "lilas" to be in both sets, which may not be the case if we do one way pairs only.

I made a [quick lookup](https://gist.github.com/yohanboniface/69f150388136111b4445056c554bb798) on the edgegrams index. We can see that around 100 keys have more than 1000 entries (that would mean 1000 candidates if we would not reduce them by pair intersection).


```diff
diff --git a/addok/autocomplete.py b/addok/autocomplete.py
index fc92f68..76aa12b 100644
--- a/addok/autocomplete.py
+++ b/addok/autocomplete.py
@@ -79,8 +79,10 @@ def autocomplete_meaningful_collector(helper):
 
 def autocomplete(helper, tokens, skip_commons=False, use_geohash=False):
     helper.debug('Autocompleting %s', helper.last_token)
-    # helper.last_token.autocomplete()
     keys = [t.db_key for t in tokens if not t.is_last]
+    # p|rue => de, du, la, chênes, …, lilas, lille…
+    # p|des => rue, chênes, …, lilas…
+    # n|lil => lilas, lille, liliputien…
     pair_keys = [pair_key(t) for t in tokens if not t.is_last]
     key = edge_ngram_key(helper.last_token)
     autocomplete_tokens = DB.sinter(pair_keys + [key])
diff --git a/addok/config/default.py b/addok/config/default.py
index d6e691c..d0fd889 100644
--- a/addok/config/default.py
+++ b/addok/config/default.py
@@ -85,7 +85,7 @@ INDEXERS_PYPATHS = [
     'addok.helpers.index.FieldsIndexer',
     # Both pairs indexers must be after `FieldsIndexer`.
     'addok.pairs.PairsIndexer',
-    'addok.pairs.HousenumbersPairsIndexer',
+    # 'addok.pairs.HousenumbersPairsIndexer',
     # Edge ngram indexer must be after `FieldsIndexer`.
     'addok.autocomplete.EdgeNgramIndexer',
     'addok.helpers.index.FiltersIndexer',
diff --git a/addok/pairs.py b/addok/pairs.py
index f789d6d..d310299 100644
--- a/addok/pairs.py
+++ b/addok/pairs.py
@@ -13,22 +13,20 @@ class PairsIndexer:
 
     @staticmethod
     def index(pipe, key, doc, tokens, **kwargs):
-        els = set(tokens.keys())  # Unique values.
-        hns = []
+        token_keys = tokens.keys()
+        tokens = list(set(token_keys))  # Unique values.
+        values = set()
         housenumbers = doc.get(config.HOUSENUMBERS_FIELD)
         if housenumbers:
             for number in housenumbers.keys():
                 for hn in preprocess(number):
-                    # Pair every document term to each housenumber, but do not pair
-                    # housenumbers together.
-                    hns.append(hn)
-        for el in els:
-            values = set(hns)
-            for el2 in els:
-                if el != el2:
-                    values.add(el2)
-            if values:
-                pipe.sadd(pair_key(el), *values)
+                    # Pair every document term to each housenumber, but do not
+                    # pair housenumbers together.
+                    pipe.sadd(pair_key(hn), *token_keys)
+                    values.add(hn)
+        tokens.sort()
+        values.update(tokens[1:])
+        pipe.sadd(pair_key(tokens[0]), *values)
 
     @staticmethod
     def deindex(db, key, doc, tokens, **kwargs):
@@ -51,19 +49,6 @@ class PairsIndexer:
 class HousenumbersPairsIndexer:
 
     @staticmethod
-    def index(pipe, key, doc, tokens, **kwargs):
-        housenumbers = doc.get(config.HOUSENUMBERS_FIELD)
-        if not housenumbers:
-            return
-        for number in housenumbers.keys():
-            for hn in preprocess(number):
-                # Pair every document term to each housenumber, but do not pair
-                # housenumbers together.
-                pipe.sadd(pair_key(hn), *tokens.keys())
-                # for key in tokens.keys():
-                #     pipe.sadd(pair_key(key), hn)
-
-    @staticmethod
     def deindex(db, key, doc, tokens, **kwargs):
         housenumbers = doc.get('housenumbers', {})
         for hn, data in housenumbers.items():
diff --git a/tests/test_index_utils.py b/tests/test_index_utils.py
index d25c125..639d59a 100644
--- a/tests/test_index_utils.py
+++ b/tests/test_index_utils.py
@@ -65,6 +65,8 @@ def test_index_document():
     assert b'lilas' in DB.smembers('p|andresy')
     assert b'andresy' in DB.smembers('p|lilas')
     assert DB.exists('p|1')
+    assert b'1' in DB.smembers('p|rue')
+    assert b'rue' in DB.smembers('p|1')
     assert DB.exists('g|u09dgm7')
     assert b'd|xxxx' in DB.smembers('g|u09dgm7')
     assert DB.exists('n|lil')
```

**Comment by yohanboniface** [comment]
About the autocomplete issue: we may create edgengram **only** for last words of document fields (only "lilas" in "rue des lilas"), and see how much it reduces the amount of candidates on a full France DB.

**Comment by yohanboniface** [comment]
Humm, but we want to be able to autocomplete "boul" in "boulevard", so that does not work.

**Pull request merged**
