### PR TITLE
Do not fail in shell if house "numbers" are not digit

### PR DESCRIPTION
**Pull request by yohanboniface**
@symroe can you have a look?

### CODE REVIEW

**Comment by symroe** [comment]
This doesn't look quite right – working on a patch now.

**Comment by yohanboniface** [comment]
OK, cool, closing here then :)

**Comment by symroe** [comment]
First couple of comments:

* `re.match(r'\d+', v).group()` will raise a `AttributeError` rather than a `TypeError`.
* `sorted(housenumbers.items(), key=sorter)` will bork when it tries to work out if a `str` < `int`. Need to return, I suggest, `-1` in the case of a house number.

**Comment by yohanboniface** [comment]
Do you want to provide a PR, as you have the data at hand to test it?
(Or I can just create one artificial document :) )
Also, I'd word on unittests for shell module, which is for now not the case.

**Comment by symroe** [comment]
See #207

**Pull request closed without merging**
