### PR TITLE
faster (homemade) ngrams

### PR DESCRIPTION
**Pull request by cquest**
simplified and faster ngrams computation without NGram module

BENCH 500 allee des acacias AUTOCOMPLETE 0
35ms > 25ms

### CODE REVIEW

**Comment by yohanboniface** [comment]
> BENCH 500 allee des acacias AUTOCOMPLETE 0

What does this command is simply to run the same search X times.
Given you've added a cache, the ngram pattern is only run once, so I'm not sure this is very informative about the overall gain.
What I'd do here is:
- have dedicated benchmarks for the ngram computation itself first (out of caching)
- have some https://github.com/geocoders/geocoder-tester runs to overview the impact

**Comment by cquest** [comment]
I expected the BENCH command to run queries indepently, resetting caches between each query... otherwise the timing is not that interesting. I'll check again if there is a real benefit.

**Comment by cquest** [comment]
I compared the NGram based version with the new one with/without cache:
- 60 us (NGram)
- 18 us (new without cache)
- 6 us (new with cache)

**Comment by yohanboniface** [comment]
Made a quick pass without touching the logic.
Though, I've changed to use a built in python LRU cache, which seems to me more appropriate: given the high variety of strings we process, I think we only want to keep the cache during a set of results processing.

On the main topic of this PR: I remember ending with ngram comparison after a whole set of tests because I found it to be the more "stable", I remember levenshtein having some edge cases notably with synonyms (bd vs boulevard for example).
Have you made some geocoder-tester runs ? If not I'll do it to see how this change is impacting.
Or if you want we can have an addok day next week and do this together :)

**Pull request closed without merging**
