### PR TITLE
Improve values handling in index and deindex methods (fixes #794)

### LINKED ISSUE #794: Addok lets you index some data that will cause a Python error during a search...
Hi !

### Our problem

When indexing on our own records into Addok, we made a mistake. As a name, we managed to index several strings within an array within an array, instead of several strings within an array (yes, just one).

`[ [ 'string1', 'string2" ] ]` instead of `[ 'string1', 'string2" ]`

It isn't detected during the indexing process... But, as soon as the rotten indexed record is collected by a search query, we have a critical Python error (it tries to lowercase a List instead of a String) and addok API answers to the search query with a 500 error. It seems to be occuring even if the record isn't included in the final list of results (being in the bucket would be enough for the rotten record to trigger the error ?).

The problem was a bit complex for us to fix as we need to provide a name when desindexing. But this array of array of strings was not accepted as an input... A true "serpent qui se mord la queue"... :D

Here is our stacktrace, seen during a search with a rotten record :
```
[ERROR] Error handling request /search?q=carm&limit=20&lat=48.626873611111165&lon=2.9462834548611063
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/addok/helpers/text.py", line 128, in _new_
cache = value._cache
AttributeError: 'list' object has no attribute '_cache'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
self.handle_request(listener, req, client, addr)
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
respiter = self.wsgi(environ, resp.start_response)
File "/usr/local/lib/python3.6/site-packages/falcon/api.py", line 227, in _call_
responder(req, resp, **params)
File "/usr/local/lib/python3.6/site-packages/addok/http/base.py", line 134, in on_get
lat=lat, lon=lon, **filters)
File "/usr/local/lib/python3.6/site-packages/addok/core.py", line 333, in search
return helper(query, lat=lat, lon=lon, **filters)
File "/usr/local/lib/python3.6/site-packages/addok/core.py", line 171, in _call_
return self.render()
File "/usr/local/lib/python3.6/site-packages/addok/core.py", line 185, in render
self.convert()
File "/usr/local/lib/python3.6/site-packages/addok/core.py", line 232, in convert
processor(self, result)
File "/usr/local/lib/python3.6/site-packages/addok/helpers/results.py", line 57, in score_by_autocomplete_distance
label = ascii(label)
File "/usr/local/lib/python3.6/site-packages/addok/helpers/text.py", line 130, in _new_
cache = alphanumerize(unidecode(value.lower()))
AttributeError: 'list' object has no attribute 'lower'
```

### A solution ?

Would'nt be nice to make the indexing process more severe regarding the given data ?

It shouldn't allow us to pass arrays of arrays of strings if it knows that it will a problem later... :D

### PR DESCRIPTION
**Pull request by AdrienVH-c2c**

### CODE REVIEW

**Comment by jdesboeufs** [comment]
Hi!

Thank you very much for your PR!

How does it behave with non-string values?

**Comment by AdrienVH-c2c** [comment]
It will raise a ValueError. Do you think that we have to deal with anything than strings here ?
I can only think about housenumbers and I am not sure they are handled by theses methods...

**Comment by AdrienVH** [comment]
As we probably need to deal with extra fields, I change a bit my implementation to accept floats and integers as well.
I also created a function to have an unique way to check types and convert values as an array.

**Comment by jdesboeufs** [comment]
I will look at this ASAP!

**Comment by AdrienVH-c2c** [comment]
@jdesboeufs @yohanboniface Up :)
We met this problem again, a few days ago. It's quite a nasty thing, as it's impossible to ask Addok to deindex the documents when they have an array of an array of string(s).

**Pull request merged**
