### PR TITLE
Fix regex order in textutils/fr_FR

### PR DESCRIPTION
**Pull request by frodrigo**

### CODE REVIEW

**Comment by yohanboniface** [comment]
Can you be a bit more explicit on what you are trying to solve?
This change is breaking the tests (in a quite easily fixable way though :) ).

**Comment by frodrigo** [comment]
I aim to support multiple space in all replacements by move the multispace replacement at the top.

**Comment by yohanboniface** [comment]
The problem is that subsequent rules can create multiple spaces.
Why are you trying to fix precisely?

**Comment by frodrigo** [comment]
I apply some other replacements in my config file.
So the solution may be to check against \s* everywhere.

**Pull request closed without merging**
